# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Test'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
  - job: build  
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      # Prepare Analysis Configuration task
    - task: SonarCloudPrepare@1
      inputs:
        scannerMode: 'MSBuild'
        SonarCloud: 'SonarCloud'
        organization: kk
        projectKey: dottest
    

    - task: DotNetCoreCLI@2
      inputs:
       command: 'build'
       projects: '**/*.csproj'
       workingDirectory: '$(System.DefaultWorkingDirectory)'
      
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'


- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
       command: 'publish'
       publishWebProjects: true
    - task: AzurePowerShell@5
      displayName: 'Create App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline:  |
          New-AzAppServicePlan -ResourceGroupName 'testaz' -Name 'MyServicePlan' -Location 'southcentralus' -Linux -Tier 'F1' 
        azurePowerShellVersion: 'LatestVersion'

    - task: AzurePowerShell@5
      displayName: 'Create Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline:  |
            New-AzWebApp -ResourceGroupName 'testaz' -Name 'testazaspdotnet' -Location 'southcentralus' -AppServicePlan 'MyServicePlan'
        azurePowerShellVersion: 'LatestVersion'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: 'testazaspdotnet'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'