# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Test'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
  - job: build  
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      # Prepare Analysis Configuration task
    - task: SonarCloudPrepare@1
      inputs:
        scannerMode: 'MSBuild'
        SonarCloud: 'SonarCloud'
        organization: kk
      
    

    - task: DotNetCoreCLI@2
      inputs:
       command: 'build'
       projects: '**/*.csproj'
       workingDirectory: '$(System.DefaultWorkingDirectory)'
      
    - task: SonarCloudAnalyze@1
  




- stage: Deploy
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
       command: 'publish'
       publishWebProjects: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: 'testazaspdotnet'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'