# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Test'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
  - job: build  
    pool:
      vmImage: ubuntu-latest
      environment: dev

    steps:
    
    - checkout: self
      path: s/azureaspdotnet   

    - task: SonarCloudPrepare@1
      inputs:
        scannerMode: 'MSBuild'
        SonarCloud: 'SonarCloud'
        organization: kk
        projectKey: dottest
    

    - task: DotNetCoreCLI@2
      inputs:
       command: 'build'
       arguments: '--no-restore --configuration $(buildConfiguration)'
       
       projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
       command: publish
       publishWebProjects: True
       arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        
       zipAfterPublish: True
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop



    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'


- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest

    steps:
    - download: current
      artifact: drop
    

    - task: AzurePowerShell@5
      displayName: 'Create App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline:  |
          New-AzAppServicePlan -ResourceGroupName 'testrguseast' -Name 'ASP-testaz-bd534' -Location 'East US' -Linux -Tier 'F1' 
        azurePowerShellVersion: 'LatestVersion'

    - task: AzurePowerShell@5
      displayName: 'Create Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline:  |
            New-AzWebApp -ResourceGroupName 'testrguseast' -Name 'testazaspdotnet' -Location 'East US' -AppServicePlan 'ASP-testaz-bd534'
        azurePowerShellVersion: 'LatestVersion'
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: 'testazaspdotnet'
        
        package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'